
include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - local: .gitlab-ci-staging-tests.yml
    rules:
      - if: $RUN_TESTS_STAGING == "true"
  - local: .gitlab-ci-default-pipeline.yml
    rules:
      - if: $RUN_TESTS_STAGING != "true"

stages:
  - test
  - build
  - publish

variables:
  RUN_TESTS_STAGING: "false"

publish:versions:
  stage: publish
  image: python:slim
  variables:
    GITHUB_TOKEN: $GITHUB_BOT_TOKEN
  before_script:
    - apt-get update && apt-get install -qqy curl hub unzip
    - pip3 install pyyaml
    - git config --global user.name mender-test-bot
    - git config --global user.email user@example.com
    - curl -fsSL https://deno.land/x/install/install.sh | sh
    - curl -sLO https://docs.mender.io/releases/versions.json
  script:
    - git for-each-ref --shell --format="tag:%(refname:short) datetime:%(creatordate:format:%s)" "refs/tags/*" | sort -V -r > tags
    - python extra/release_info_generator.py
    - /root/.deno/bin/deno fmt versions.json
    - hub clone mendersoftware/mender-docs-site && mv versions.json mender-docs-site/versions.json && cd mender-docs-site
    - "git add versions.json && git commit --signoff -m 'chore: Version information update' -m 'Changelog: None'"
    - hub pull-request --push --draft --base mendersoftware/mender-docs-site --message "Version information update" --message "keeping up with the versions"
  artifacts:
    expire_in: 2w
    paths:
      - versions.json
  rules:
    - if: $CI_COMMIT_TAG
