
include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - local: .gitlab-ci-staging-tests.yml
    rules:
      - if: $RUN_TESTS_STAGING == "true"
  - local: .gitlab-ci-default-pipeline.yml
    rules:
      - if: $RUN_TESTS_STAGING != "true"

stages:
  - test
  - build
  - publish

variables:
  RUN_TESTS_STAGING: "false"
