version: '2.1'
services:

    #
    # auditlogs
    #
    mender-auditlogs:
        image: registry.mender.io/mendersoftware/auditlogs:mender-2.6.0
        networks:
            - mender
        depends_on:
            - mender-mongo
        command: server --automigrate

    mender-api-gateway:
        environment:
            HAVE_AUDITLOGS: 1

    mender-useradm:
        environment:
            USERADM_ENABLE_AUDIT: 1

    mender-deployments:
        environment:
            DEPLOYMENTS_ENABLE_AUDIT: 1

    mender-workflows-worker:
        environment:
            HAVE_AUDITLOGS: 1
