version: '2.1'
services:

    #
    # mender-client
    #
    mender-client:
        image: mendersoftware/mender-client-qemu:2.6.x
        networks:
            - mender
        stdin_open: true
        tty: true
        privileged: true
        environment:
          TENANT_TOKEN:
