version: '2.1'
services:


    #
    # mender-azure-iot-manager
    #
    mender-azure-iot-manager:
        image: mendersoftware/azure-iot-manager:mender-master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
        labels:
            mender.healthcheck.path: "/api/internal/v1/azure-iot-manager/health"
