version: '2.1'
services:

    mender-client:
        # Needs to be built in mender client's test directory.
        image: mendersoftware/mender-client-docker:3.2.x
        networks:
            - mender

networks:
    mender:
