version: '2.1'
services:

    #
    # minio
    #
    minio:
        image: minio/minio:RELEASE.2019-04-23T23-50-36Z
        restart: on-failure
        networks:
            mender:
                aliases:
                    - minio.s3.docker.mender.io
        environment:
            MINIO_HTTP_TRACE: /dev/stdout
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.minio.entrypoints=https"
            - "traefik.http.routers.minio.rule=PathPrefix(`/mender-artifact-storage`)||HeadersRegexp(`X-Amz-Date`, `.+`)"
            - "traefik.http.routers.minio.tls=true"
            - "traefik.http.services.minio.loadbalancer.server.port=9000"
            - mender.testprefix=${MENDER_TESTPREFIX:-""}
        command: server /export

    #
    # mender-deployments depends on minio if minio is in use
    #
    mender-deployments:
        depends_on:
            minio:
                condition: service_healthy
