version: '2.1'

services:
    mender-deviceconfig:
        image: mendersoftware/deviceconfig:mender-master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
        command: server --automigrate
        labels:
            - traefik.enable=true
            - traefik.http.routers.deviceconfig.entrypoints=https
            - traefik.http.routers.deviceconfig.middlewares=userauth,sec-headers,json-error-responder1,json-error-responder4
            - traefik.http.routers.deviceconfig.rule=PathPrefix(`/api/management/{(v[0-9]+)}/deviceconfig`)
            - traefik.http.routers.deviceconfig.tls=true
            - traefik.http.routers.deviceconfig.service=deviceconfig
            - traefik.http.services.deviceconfig.loadbalancer.server.port=8080
            - mender.testprefix=${MENDER_TESTPREFIX}

    mender-api-gateway:
        environment:
            HAVE_DEVICECONFIG: 1
