version: '2.1'
services:

    # subsitute services with 'enterprise' versions
    mender-deployments:
        image: registry.mender.io/mendersoftware/deployments-enterprise:mender-2.7.1

    mender-inventory:
        image: registry.mender.io/mendersoftware/inventory-enterprise:mender-2.7.1

    mender-workflows-server:
        image: registry.mender.io/mendersoftware/workflows-enterprise:mender-2.7.1

    mender-workflows-worker:
        image: registry.mender.io/mendersoftware/workflows-enterprise-worker:mender-2.7.1

    # add services
    mender-tenantadm:
        image: registry.mender.io/mendersoftware/tenantadm:mender-2.7.1
        environment:
            TENANTADM_ORCHESTRATOR_ADDR: http://mender-workflows-server:8080/
        extends:
            file: common.yml
            service: mender-base
        labels:
            - traefik.enable=true
            - traefik.http.routers.tenantadm.entrypoints=https
            - traefik.http.routers.tenantadm.middlewares=userauth,sec-headers,compression
            - traefik.http.routers.tenantadm.rule=PathPrefix(`/api/management/{v[0-9]+}/tenantadm`)
            - traefik.http.routers.tenantadm.tls=true
            - traefik.http.routers.tenantadm.service=tenantadm
            - traefik.http.services.tenantadm.loadbalancer.server.port=8080

            - traefik.http.routers.tenantadmSignup.entrypoints=https
            - traefik.http.routers.tenantadmSignup.middlewares=sec-headers,compression
            - traefik.http.routers.tenantadmSignup.rule=Path(`/api/management/{v[0-9]+}/tenantadm/tenants`) || Path(`/api/management/{v[0-9]+}/tenantadm/tenants/trial`) && Method(`OPTIONS`,`POST`)
            - traefik.http.routers.tenantadmSignup.tls=true
            - traefik.http.routers.tenantadmSignup.service=tenantadm
            - mender.testprefix=${MENDER_TESTPREFIX:-""}
        networks:
            - mender
        depends_on:
            - mender-mongo

    # configure the rest
    mender-device-auth:
        environment:
            DEVICEAUTH_TENANTADM_ADDR: 'http://mender-tenantadm:8080'
            DEVICEAUTH_HAVE_ADDONS: 1

    mender-useradm:
        image: registry.mender.io/mendersoftware/useradm-enterprise:mender-2.7.1
        environment:
            USERADM_TENANTADM_ADDR: 'http://mender-tenantadm:8080'
            USERADM_HAVE_ADDONS: 1

    mender-api-gateway:
        environment:
            HAVE_MULTITENANT: 1

    mender-gui:
        environment:
            HAVE_MULTITENANT: 1
            HAVE_ENTERPRISE: 1

networks:
    mender:
