version: '2.1'
services:

    mender-client:
        # Needs to be built in mender client's test directory.
        image: mendersoftware/mender-client-docker:mender-3.3.0
        networks:
            - mender

networks:
    mender:
