version: '2.1'
services:

    #
    # auditlogs
    #
    mender-auditlogs:
        image: registry.mender.io/mendersoftware/auditlogs:mender-master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
        command: server --automigrate

    mender-api-gateway:
      volumes:
        - ./config/traefik/traefik.auditlogs.yaml:/etc/traefik/config/traefik.auditlogs.yaml:ro

    mender-useradm:
        environment:
            USERADM_ENABLE_AUDIT: 1

    mender-deployments:
        environment:
            DEPLOYMENTS_ENABLE_AUDIT: 1

    mender-workflows-worker:
        environment:
            HAVE_AUDITLOGS: 1
