version: '2.1'
services:

    # subsitute services with 'enterprise' versions
    mender-deployments:
        image: registry.mender.io/mendersoftware/deployments-enterprise:mender-3.0.3-build3

    mender-inventory:
        image: registry.mender.io/mendersoftware/inventory-enterprise:mender-3.0.3-build3

    mender-workflows-server:
        image: registry.mender.io/mendersoftware/workflows-enterprise:mender-3.0.3-build3

    mender-workflows-worker:
        image: registry.mender.io/mendersoftware/workflows-enterprise-worker:mender-3.0.3-build3

    # add services
    mender-tenantadm:
        image: registry.mender.io/mendersoftware/tenantadm:mender-3.0.3-build3
        environment:
            TENANTADM_ORCHESTRATOR_ADDR: http://mender-workflows-server:8080/
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    # configure the rest
    mender-device-auth:
        environment:
            DEVICEAUTH_TENANTADM_ADDR: 'http://mender-tenantadm:8080'
            DEVICEAUTH_HAVE_ADDONS: 1

    mender-useradm:
        image: registry.mender.io/mendersoftware/useradm-enterprise:mender-3.0.3-build3
        environment:
            USERADM_TENANTADM_ADDR: 'http://mender-tenantadm:8080'
            USERADM_HAVE_ADDONS: 1

    mender-api-gateway:
      volumes:
        - ./config/traefik/traefik.enterprise.yaml:/etc/traefik/config/traefik.enterprise.yaml:ro

    mender-gui:
        environment:
            HAVE_MULTITENANT: 1
            HAVE_ENTERPRISE: 1

networks:
    mender:
