version: '2.3'
services:

    mender-client:
        # Needs to be built in extra/mender-client-docker-addons
        image: mendersoftware/mender-client-docker-addons:mender-3.4.0
        networks:
            - mender

networks:
    mender:
