version: '2.1'
services:

    # add services
    mender-tenantadm:
        image: registry.mender.io/mendersoftware/tenantadm:staging
        environment:
            TENANTADM_ORCHESTRATOR_ADDR: http://mender-workflows-server:8080/
        extends:
            file: common.yml
            service: mender-base
        labels:
            - traefik.enable=true
            - traefik.http.routers.tenantadm.entrypoints=https
            - traefik.http.routers.tenantadm.middlewares=userauth,sec-headers,compression
            - traefik.http.routers.tenantadm.rule=PathPrefix(`/api/management/{(v[0-9]+)}/tenantadm`)
            - traefik.http.routers.tenantadm.tls=true
            - traefik.http.routers.tenantadm.service=tenantadm
            - traefik.http.services.tenantadm.loadbalancer.server.port=8080

            - traefik.http.routers.tenantadmMgmt.entrypoints=https
            - traefik.http.routers.tenantadmMgmt.middlewares=sec-headers,compression
            - traefik.http.routers.tenantadmMgmt.rule=PathPrefix(`/api/management/{(v[0-9]+)}/tenantadm/tenants`) && Method(`OPTIONS`,`POST`,`PUT`,`DELETE`)
            - traefik.http.routers.tenantadmMgmt.tls=true
            - traefik.http.routers.tenantadmMgmt.service=tenantadmMgmt
            - traefik.http.services.tenantadmMgmt.loadbalancer.server.port=8080
            - mender.testprefix=${MENDER_TESTPREFIX:-""}
        networks:
            - mender
        depends_on:
            - mender-mongo

    # configure the rest
    mender-device-auth:
        environment:
            DEVICEAUTH_TENANTADM_ADDR: 'http://mender-tenantadm:8080'

    mender-useradm:
        environment:
            USERADM_TENANTADM_ADDR: 'http://mender-tenantadm:8080'

    mender-api-gateway:
        environment:
            HAVE_MULTITENANT: 1

    mender-gui:
        environment:
            HAVE_MULTITENANT: 1
            HAVE_ENTERPRISE: 1

networks:
    mender:
