version: '2.1'
services:

    #
    # monitor-client
    #
    mender-client:
        image: registry.mender.io/mendersoftware/mender-monitor-qemu-commercial:mender-3.2.x
        networks:
            - mender
        stdin_open: true
        tty: true
        privileged: true
        environment:
            - TENANT_TOKEN=$TENANT_TOKEN
