http:
  routers:

    #
    # deviceconfig
    #
    deviceconfig:
      entrypoints: https
      middlewares: #{{- block "circuit-breaker" . -}}{{- if not (env "TESTING") }}
      - circuit-breaker #{{- end}}{{end}}
      - devauth
      - sec-headers
      - compression
      - json-error-responder1
      - json-error-responder2
      - json-error-responder3
      - json-error-responder4
      rule: "PathPrefix(`/api/devices/{version:v[0-9]+}/deviceconfig`)"
      service: deviceconfig
      tls: true

    deviceconfigMgmt:
      entrypoints: https
      middlewares: #{{- template "circuit-breaker"}}
      - userauth
      - sec-headers
      - compression
      - json-error-responder1
      - json-error-responder4
      rule: "PathPrefix(`/api/management/{version:v[0-9]+}/deviceconfig`)"
      service: deviceconfig
      tls: true

    #
    # devicemonitor
    #
    devicemonitor:
      entrypoints: https
      middlewares:
      - devauth
      - sec-headers
      - compression
      - json-error-responder1
      - json-error-responder2
      - json-error-responder3
      - json-error-responder4
      rule: "PathPrefix(`/api/devices/{version:v[0-9]+}/devicemonitor`)"
      service: devicemonitor
      tls: true

    devicemonitorMgmt:
      entrypoints: https
      middlewares:
      - userauth
      - sec-headers
      - compression
      - json-error-responder1
      - json-error-responder4
      rule: "PathPrefix(`/api/management/{version:v[0-9]+}/devicemonitor`)"
      service: devicemonitor
      tls: true

  services:

    devicemonitor:
      loadBalancer:
        servers:
        - url: "http://mender-devicemonitor:8080"

    deviceconfig:
      loadBalancer:
        servers:
        - url: "http://mender-deviceconfig:8080"

