tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.crt
        keyFile: /etc/traefik/certs/private.key

  certificates:
    - certFile: /etc/traefik/certs/s3.docker.mender.io.crt
      keyFile: /etc/traefik/certs/s3.docker.mender.io.key
      stores:
        - default
