version: '2.1'
services:
  mender-gateway:
    image: registry.mender.io/mendersoftware/mender-gateway:master
    networks:
      - mender
      - mender_local
    volumes:
      - "./extra/mender-gateway/mender-gateway.conf:/etc/mender/mender-gateway.conf:ro"

networks:
    mender:
    mender_local:
